package com.bilibili.studio.videoeditor.template.bean;

import android.os.Parcel;
import android.os.Parcelable;
import androidx.annotation.Keep;
import com.alibaba.fastjson.annotation.JSONField;
import java.io.Serializable;
import java.util.Arrays;
import v.C8770a;

/* JADX INFO: loaded from: bili_base.jar:com/bilibili/studio/videoeditor/template/bean/BiliEditorBean.class */
@Keep
public class BiliEditorBean implements Serializable, Parcelable {
    public static final Parcelable.Creator<BiliEditorBean> CREATOR = new Object();
    public int ai_matting_pic;
    public int ai_matting_video;
    public String algo_script;
    public int audio_record;
    public String backgrounds;
    public int bezier;
    public String bgms;
    public String colormatting_from;
    public int cover_templates;
    public int default_end;
    public int diy_drawing;
    public long duration;
    public String effects;
    public String feature_source;
    public String features;
    public String filters;
    public String flowers;
    public String fonts;
    public String game_aicut;
    public boolean highlight;
    public int highlight_cnt;
    public String highlightgame;
    public String hot_topic_effects;
    public String hot_topic_videos;
    public int isalign;
    public boolean isreplace;
    public int isvideomarked;
    public String keyframe_audio;
    public int keyframe_audio_count;
    public String keyframe_clip;
    public int keyframe_clip_count;
    public String keyframe_pip;
    public int keyframe_pip_count;
    public String keyframe_sticker;
    public int keyframe_sticker_count;
    public String keyframe_subtitle;
    public int keyframe_subtitle_count;
    public String kichiku;
    public int kichiku_lines;
    public String kichiku_opening;
    public String kichiku_scene;
    public String[] material_up_froms;
    public String noise_cancel;
    public String openings;
    public int pic_count;
    public int pip_count;
    public String process_bar;
    public int quickmatch;
    public boolean record_text;
    public int screen_record;
    public String script_result;
    public String selectedBgms;
    public String selectedVideos;
    public long shot_duration;
    public String shot_game;
    public String sounds;
    public int speed;
    public String subtitles;
    public String text_to_video;
    public String text_to_video_source;
    public String textmotion_id;
    public String trans;
    public String tts;
    public String video_animation_ending;
    public String video_animation_mix;
    public String video_animation_opening;
    public int video_count;
    public String video_templates_full;
    public String video_templates_start;
    public int videomarkcount;
    public String videos;
    public String videoup_stickers;
    public String virtual_bg;
    public String virtual_idol_template;
    public String virtual_prop;

    @JSONField(deserialize = false, serialize = false)
    public String vupElements;
    public long[] vup_action;
    public long[] vup_combine;
    public long[] vup_exp;
    public String vupers;

    /* JADX INFO: loaded from: bili_base.jar:com/bilibili/studio/videoeditor/template/bean/BiliEditorBean$a.class */
    public final class a implements Parcelable.Creator<BiliEditorBean> {
        @Override // android.os.Parcelable.Creator
        public final BiliEditorBean createFromParcel(Parcel parcel) {
            return new BiliEditorBean(parcel);
        }

        @Override // android.os.Parcelable.Creator
        public final BiliEditorBean[] newArray(int i7) {
            return new BiliEditorBean[i7];
        }
    }

    public BiliEditorBean() {
        this.quickmatch = 0;
        this.cover_templates = -10086;
        this.colormatting_from = "";
        this.keyframe_clip_count = 0;
        this.keyframe_clip = "";
        this.keyframe_pip_count = 0;
        this.keyframe_pip = "";
        this.keyframe_subtitle_count = 0;
        this.keyframe_subtitle = "";
        this.keyframe_sticker_count = 0;
        this.keyframe_sticker = "";
        this.keyframe_audio_count = 0;
        this.keyframe_audio = "";
        this.bezier = 0;
        this.algo_script = "";
        this.script_result = "";
        this.ai_matting_pic = 0;
        this.ai_matting_video = 0;
    }

    public BiliEditorBean(Parcel parcel) {
        this.quickmatch = 0;
        this.cover_templates = -10086;
        this.colormatting_from = "";
        this.keyframe_clip_count = 0;
        this.keyframe_clip = "";
        this.keyframe_pip_count = 0;
        this.keyframe_pip = "";
        this.keyframe_subtitle_count = 0;
        this.keyframe_subtitle = "";
        this.keyframe_sticker_count = 0;
        this.keyframe_sticker = "";
        this.keyframe_audio_count = 0;
        this.keyframe_audio = "";
        this.bezier = 0;
        this.algo_script = "";
        this.script_result = "";
        this.ai_matting_pic = 0;
        this.ai_matting_video = 0;
        this.videos = parcel.readString();
        this.backgrounds = parcel.readString();
        this.filters = parcel.readString();
        this.fonts = parcel.readString();
        this.subtitles = parcel.readString();
        this.bgms = parcel.readString();
        this.videoup_stickers = parcel.readString();
        this.trans = parcel.readString();
        this.effects = parcel.readString();
        this.features = parcel.readString();
        this.material_up_froms = parcel.createStringArray();
        this.sounds = parcel.readString();
        this.pic_count = parcel.readInt();
        this.video_count = parcel.readInt();
        this.duration = parcel.readLong();
        this.default_end = parcel.readInt();
        this.speed = parcel.readInt();
        this.audio_record = parcel.readInt();
        this.screen_record = parcel.readInt();
        this.pip_count = parcel.readInt();
        this.highlight_cnt = parcel.readInt();
        this.highlight = parcel.readByte() != 0;
        this.record_text = parcel.readByte() != 0;
        this.flowers = parcel.readString();
        this.textmotion_id = parcel.readString();
        this.cover_templates = parcel.readInt();
        this.tts = parcel.readString();
        this.isreplace = parcel.readByte() != 0;
        this.openings = parcel.readString();
        this.video_templates_start = parcel.readString();
        this.video_templates_full = parcel.readString();
        this.vupers = parcel.readString();
        this.vupElements = parcel.readString();
        this.vup_exp = parcel.createLongArray();
        this.vup_action = parcel.createLongArray();
        this.vup_combine = parcel.createLongArray();
        this.diy_drawing = parcel.readInt();
        this.quickmatch = parcel.readInt();
        this.game_aicut = parcel.readString();
        this.kichiku_lines = parcel.readInt();
        this.kichiku_opening = parcel.readString();
        this.keyframe_clip_count = parcel.readInt();
        this.keyframe_pip_count = parcel.readInt();
        this.keyframe_subtitle_count = parcel.readInt();
        this.keyframe_sticker_count = parcel.readInt();
        this.keyframe_audio_count = parcel.readInt();
        this.ai_matting_pic = parcel.readInt();
        this.ai_matting_video = parcel.readInt();
        this.algo_script = parcel.readString();
        this.script_result = parcel.readString();
        this.selectedVideos = parcel.readString();
        this.selectedBgms = parcel.readString();
    }

    @Override // android.os.Parcelable
    public int describeContents() {
        return 0;
    }

    public String toString() {
        StringBuilder sb = new StringBuilder("BiliEditorBean{videos='");
        sb.append(this.videos);
        sb.append("', backgrounds='");
        sb.append(this.backgrounds);
        sb.append("', filters='");
        sb.append(this.filters);
        sb.append("', fonts='");
        sb.append(this.fonts);
        sb.append("', subtitles='");
        sb.append(this.subtitles);
        sb.append("', bgms='");
        sb.append(this.bgms);
        sb.append("', videoup_stickers='");
        sb.append(this.videoup_stickers);
        sb.append("', trans='");
        sb.append(this.trans);
        sb.append("', effects='");
        sb.append(this.effects);
        sb.append("', features='");
        sb.append(this.features);
        sb.append("', material_up_froms=");
        sb.append(Arrays.toString(this.material_up_froms));
        sb.append(", kichiku='");
        sb.append(this.kichiku);
        sb.append("', kichiku_scene='");
        sb.append(this.kichiku_scene);
        sb.append("', kichiku_lines=");
        sb.append(this.kichiku_lines);
        sb.append(", kichiku_opening='");
        sb.append(this.kichiku_opening);
        sb.append("', process_bar='");
        sb.append(this.process_bar);
        sb.append("', quickmatch=");
        sb.append(this.quickmatch);
        sb.append(", sounds='");
        sb.append(this.sounds);
        sb.append("', pic_count=");
        sb.append(this.pic_count);
        sb.append(", video_count=");
        sb.append(this.video_count);
        sb.append(", duration=");
        sb.append(this.duration);
        sb.append(", default_end=");
        sb.append(this.default_end);
        sb.append(", speed=");
        sb.append(this.speed);
        sb.append(", audio_record=");
        sb.append(this.audio_record);
        sb.append(", screen_record=");
        sb.append(this.screen_record);
        sb.append(", shot_duration=");
        sb.append(this.shot_duration);
        sb.append(", shot_game='");
        sb.append(this.shot_game);
        sb.append("', pip_count=");
        sb.append(this.pip_count);
        sb.append(", highlight_cnt=");
        sb.append(this.highlight_cnt);
        sb.append(", highlight=");
        sb.append(this.highlight);
        sb.append(", highlightgame='");
        sb.append(this.highlightgame);
        sb.append("', flowers='");
        sb.append(this.flowers);
        sb.append("', textmotion_id='");
        sb.append(this.textmotion_id);
        sb.append("', record_text=");
        sb.append(this.record_text);
        sb.append(", cover_templates=");
        sb.append(this.cover_templates);
        sb.append(", noise_cancel='");
        sb.append(this.noise_cancel);
        sb.append("', tts='");
        sb.append(this.tts);
        sb.append("', isreplace=");
        sb.append(this.isreplace);
        sb.append(", openings='");
        sb.append(this.openings);
        sb.append("', video_templates_full='");
        sb.append(this.video_templates_full);
        sb.append("', video_templates_start='");
        sb.append(this.video_templates_start);
        sb.append("', game_aicut='");
        sb.append(this.game_aicut);
        sb.append("', text_to_video='");
        sb.append(this.text_to_video);
        sb.append("', text_to_video_source='");
        sb.append(this.text_to_video_source);
        sb.append("', virtual_idol_template='");
        sb.append(this.virtual_idol_template);
        sb.append("', feature_source='");
        sb.append(this.feature_source);
        sb.append("', videomarkcount=");
        sb.append(this.videomarkcount);
        sb.append(", isvideomarked=");
        sb.append(this.isvideomarked);
        sb.append(", isalign=");
        sb.append(this.isalign);
        sb.append(", vupers='");
        sb.append(this.vupers);
        sb.append("', vupElements='");
        sb.append(this.vupElements);
        sb.append("', vup_exp=");
        sb.append(Arrays.toString(this.vup_exp));
        sb.append(", vup_action=");
        sb.append(Arrays.toString(this.vup_action));
        sb.append(", vup_combine=");
        sb.append(Arrays.toString(this.vup_combine));
        sb.append(", diy_drawing=");
        sb.append(this.diy_drawing);
        sb.append(", colormatting_from='");
        sb.append(this.colormatting_from);
        sb.append("', hot_topic_effects='");
        sb.append(this.hot_topic_effects);
        sb.append("', hot_topic_videos='");
        sb.append(this.hot_topic_videos);
        sb.append("', keyframe_clip_count=");
        sb.append(this.keyframe_clip_count);
        sb.append(", keyframe_clip='");
        sb.append(this.keyframe_clip);
        sb.append("', keyframe_pip_count=");
        sb.append(this.keyframe_pip_count);
        sb.append(", keyframe_pip='");
        sb.append(this.keyframe_pip);
        sb.append("', keyframe_subtitle_count=");
        sb.append(this.keyframe_subtitle_count);
        sb.append(", keyframe_subtitle='");
        sb.append(this.keyframe_subtitle);
        sb.append("', keyframe_sticker_count=");
        sb.append(this.keyframe_sticker_count);
        sb.append(", keyframe_sticker='");
        sb.append(this.keyframe_sticker);
        sb.append("', keyframe_audio_count=");
        sb.append(this.keyframe_audio_count);
        sb.append(", keyframe_audio='");
        sb.append(this.keyframe_audio);
        sb.append("', bezier=");
        sb.append(this.bezier);
        sb.append(", algo_script='");
        sb.append(this.algo_script);
        sb.append("', script_result='");
        sb.append(this.script_result);
        sb.append("', video_animation_opening='");
        sb.append(this.video_animation_opening);
        sb.append("', video_animation_ending='");
        sb.append(this.video_animation_ending);
        sb.append("', video_animation_mix='");
        sb.append(this.video_animation_mix);
        sb.append("', ai_matting_pic=");
        sb.append(this.ai_matting_pic);
        sb.append(", ai_matting_video=");
        sb.append(this.ai_matting_video);
        sb.append(", virtual_bg='");
        sb.append(this.virtual_bg);
        sb.append("', virtual_prop='");
        return C8770a.a(sb, this.virtual_prop, "'}");
    }

    @Override // android.os.Parcelable
    public void writeToParcel(Parcel parcel, int i7) {
        parcel.writeString(this.videos);
        parcel.writeString(this.backgrounds);
        parcel.writeString(this.filters);
        parcel.writeString(this.fonts);
        parcel.writeString(this.subtitles);
        parcel.writeString(this.bgms);
        parcel.writeString(this.videoup_stickers);
        parcel.writeString(this.trans);
        parcel.writeString(this.effects);
        parcel.writeString(this.features);
        parcel.writeStringArray(this.material_up_froms);
        parcel.writeString(this.sounds);
        parcel.writeInt(this.pic_count);
        parcel.writeInt(this.video_count);
        parcel.writeLong(this.duration);
        parcel.writeInt(this.default_end);
        parcel.writeInt(this.speed);
        parcel.writeInt(this.audio_record);
        parcel.writeInt(this.screen_record);
        parcel.writeInt(this.pip_count);
        parcel.writeInt(this.highlight_cnt);
        parcel.writeByte(this.highlight ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.record_text ? (byte) 1 : (byte) 0);
        parcel.writeString(this.flowers);
        parcel.writeString(this.textmotion_id);
        parcel.writeInt(this.cover_templates);
        parcel.writeString(this.tts);
        parcel.writeByte(this.isreplace ? (byte) 1 : (byte) 0);
        parcel.writeString(this.openings);
        parcel.writeString(this.video_templates_start);
        parcel.writeString(this.video_templates_full);
        parcel.writeString(this.vupers);
        parcel.writeString(this.vupElements);
        parcel.writeLongArray(this.vup_exp);
        parcel.writeLongArray(this.vup_action);
        parcel.writeLongArray(this.vup_combine);
        parcel.writeInt(this.diy_drawing);
        parcel.writeInt(this.quickmatch);
        parcel.writeString(this.game_aicut);
        parcel.writeInt(this.kichiku_lines);
        parcel.writeString(this.kichiku_opening);
        parcel.writeInt(this.keyframe_clip_count);
        parcel.writeInt(this.keyframe_pip_count);
        parcel.writeInt(this.keyframe_subtitle_count);
        parcel.writeInt(this.keyframe_sticker_count);
        parcel.writeInt(this.keyframe_audio_count);
        parcel.writeInt(this.ai_matting_pic);
        parcel.writeInt(this.ai_matting_video);
        parcel.writeString(this.algo_script);
        parcel.writeString(this.script_result);
        parcel.writeString(this.selectedVideos);
        parcel.writeString(this.selectedBgms);
    }
}
